--- #YAML:1.0
name:               Dancer
version:            1.1808
abstract:           A minimal-effort oriented web application framework
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Encode:               0
    File::Basename:       0
    File::Spec:           0
    HTTP::Body:           1.07
    HTTP::Server::Simple::PSGI:  0.11
    MIME::Types:          0
    Test::More:           0.88
    Time::HiRes:          0
    URI:                  0
resources:
    bugtracker:  http://github.com/sukria/Dancer/issues
    homepage:    http://perldancer.org/
    repository:  http://github.com/sukria/Dancer
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
