---
abstract: 'A minimal-effort oriented web application framework'
author:
  - unknown
build_requires:
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer
no_index:
  directory:
    - t
    - inc
requires:
  Encode: 0
  File::Basename: 0
  File::Spec: 0
  HTTP::Body: 1.07
  HTTP::Server::Simple::PSGI: 0.11
  LWP: 0
  MIME::Types: 0
  Module::Runtime: 0
  Time::HiRes: 0
  Try::Tiny: 0.09
  URI: 1.59
resources:
  bugtracker: https://github.com/PerlDancer/Dancer/issues
  homepage: http://perldancer.org/
  repository: https://github.com/PerlDancer/Dancer
version: 1.3112
