--- #YAML:1.0
name:                Dancer
version:             1.175
abstract:            A minimal-effort oriented web application framework
license:             perl
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    File::Basename:                0
    File::Spec:                    0
    HTTP::Body:                    0
    HTTP::Server::Simple::PSGI:    0.11
    MIME::Types:                   0
    Test::More:                    0.87
    URI:                           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
